
--physically stores data
CREATE MATERIALIZED VIEW site_schema.template_site_summary_metrics_mat AS
SELECT *
FROM site_schema.template_site_summary_metrics;

CREATE INDEX template_site_summary_metrics_mat_site_id_idx ON site_schema.template_site_summary_metrics_mat (site_id);
CREATE INDEX template_site_summary_metrics_mat_month_year_idx ON site_schema.template_site_summary_metrics_mat (report_month, report_year);

--REFRESH MATERIALIZED VIEW site_schema.template_site_summary_metrics_mat;

